# Generated by Django 3.0.6 on 2020-06-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('bangla', 'Bangla')], default='english', max_length=20),
        ),
    ]
