# Generated by Django 3.0.6 on 2020-05-31 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='loge',
            field=models.ImageField(blank=True, upload_to='sitesettings/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mypic1',
            field=models.ImageField(blank=True, upload_to='sitesettings/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mypic2',
            field=models.ImageField(blank=True, upload_to='sitesettings/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mypic3',
            field=models.ImageField(blank=True, upload_to='sitesettings/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mypic4',
            field=models.ImageField(blank=True, upload_to='sitesettings/%Y/%m/%d'),
        ),
    ]
