# Generated by Django 3.0.6 on 2020-05-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20200601_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='name',
            field=models.CharField(default='sitesettings', max_length=100),
        ),
    ]
